### ISSUE TITLE
Ignoring continuation in GeneratorController 

### ISSUE THREAD

**Issue by ilya-g** [kotlin-es/coroutine-examples#1]
It looks suspicious that you're ignoring continuations passed to the `GeneratorController` and instead resuming execution to the first continuation returned by coroutine.
https://github.com/kotlin-es/coroutine-examples/blob/b7afceb/src/es/kotlin/collection/coroutine/generate.kt#L32

```
class GeneratorController<T> {
    var lastValue: T? = null
    var done: Boolean = false
    suspend fun yield(value:T, x: Continuation<Unit>) {
        lastValue = value
    }
    operator fun handleResult(x: Unit, y: Continuation<Nothing>) {
        done = true
    }
}
```

Does it work as expected?

**Comment by soywiz** [comment]
Uhm. That's right! Indeed seems strange.

And Yeah. It works.
And it works because it is always Unit. The integer field that handles the state resume point changes before suspending the function and the continuation call just resumes the function with a value, so it makes sense that it works specially because type erasure, it (`x: Continuation<Unit>`) will be the same object all the time but compiler uses that information to cast the continued parameter.

But anyway I will change it.
